name = "buysell-best"
compatibility_date = "2026-09-20"
main = "./worker.js"

[assets]
directory = "."
binding = "ASSETS"
run_worker_first = ["/api/*"]

[[d1_databases]]
binding = "DB"
database_name = "buysell-best-db"
database_id = "822532f2-1e71-41c5-8d3b-0b678c903e0a"
